"""empty message

Revision ID: 2364ac6abca4
Revises: ebec6e5f1c6c
Create Date: 2024-07-18 22:50:26.523308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2364ac6abca4'
down_revision: Union[str, None] = 'ebec6e5f1c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('api_key_secret', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key_secret')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
