"""empty message

Revision ID: 9512308d55cf
Revises: 2364ac6abca4
Create Date: 2024-07-18 22:51:39.210021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9512308d55cf'
down_revision: Union[str, None] = '2364ac6abca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.TEXT(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
