"""empty message

Revision ID: c34811630b7f
Revises: 88828f02f9ff
Create Date: 2024-07-15 21:42:03.854996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34811630b7f'
down_revision = '88828f02f9ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
