"""Create users and item tables

Revision ID: d32715d6806c
Revises: 9cdf5c38aaeb
Create Date: 2024-08-01 16:21:00.103951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32715d6806c'
down_revision = '9cdf5c38aaeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
