"""empty message

Revision ID: 6f94d27eb622
Revises: 
Create Date: 2024-07-14 17:34:31.678724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f94d27eb622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('api_secret', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('position_type', sa.Boolean(), nullable=False),
    sa.Column('enter_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('purchase_percent', sa.Float(), nullable=False),
    sa.Column('eval_price', sa.Float(), nullable=False),
    sa.Column('eval_PAL', sa.Float(), nullable=False),
    sa.Column('revenue_rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('profit_end', sa.Float(), nullable=False),
    sa.Column('loss_end', sa.Float(), nullable=False),
    sa.Column('onwer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onwer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user')
    # ### end Alembic commands ###
