"""Rename purchase_percent to purchase_price

Revision ID: 88828f02f9ff
Revises: b14b26de5503
Create Date: 2024-07-15 16:17:11.458602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88828f02f9ff'
down_revision = 'b14b26de5503'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'purchase_percent', new_column_name='purchase_price')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'purchase_price', new_column_name='purchase_percent')

    # ### end Alembic commands ###
