"""empty message

Revision ID: b14b26de5503
Revises: 6f94d27eb622
Create Date: 2024-07-15 16:13:48.352986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14b26de5503'
down_revision = '6f94d27eb622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
